name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE: registry.speechanddebate.org/indexcards

jobs:
  jobs:
  build-indexcards:
    uses: ./.forgejo/actions/build-docker.yml
    with:
      image: indexcards
      dockerfile: indexcards/Dockerfile

  build-schemats:
    uses: ./.forgejo/actions/build-docker.yml
    with:
      image: schemats
      dockerfile: schemats/Dockerfile

  publish:
      runs-on: linux-amd64
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v6
        - uses: ./.forgejo/actions/docker-publish
          with:
            image: indexcards
            registry_username: ${{ secrets.REGISTRY_USERNAME }}
            registry_password: ${{ secrets.REGISTRY_PASSWORD }}
