name: Build Docker Image

inputs:
  image:
    required: true
    description: Docker image name

  dockerfile:
    required: true
    description: Path to Dockerfile

runs:
  using: composite
  steps:
    - name: Build image
      shell: bash
      run: |
        docker build \
          -f "${{ inputs.dockerfile }}" \
          -t "${{ inputs.image }}:${FORGEJO_SHA}" \
          -t "${{ inputs.image }}:production" \
          .
