/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { CurrentBallotEntriesItem } from './currentBallotEntriesItem';
import type { CurrentBallotEventType } from './currentBallotEventType';
import type { CurrentBallotFlipStatus } from './currentBallotFlipStatus';
import type { CurrentBallotStatus } from './currentBallotStatus';

export interface CurrentBallot {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	name: number | null;
	label: string | null;
	flipStatus: CurrentBallotFlipStatus;
	/** null if not flighted. otherwise flight num. */
	flight: number | null;
	show_async: boolean;
	/** true if the tournament uses online ballots */
	onlineBallots: boolean;
	legion: boolean;
	start: string;
	deadline: string;
	roomId: number | null;
	roomName: string | null;
	roomUrl: string | null;
	roomNotes: string | null;
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	JudgeId: number;
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	RoundId: number;
	status: CurrentBallotStatus;
	startText: string | null;
	ballotText: string | null;
	chair: boolean;
	audited: boolean;
	/** @maxLength 31 */
	TournTz: string;
	eventType: CurrentBallotEventType;
	/** @nullable */
	onlineMode: string | null;
	Entries: CurrentBallotEntriesItem[];
}
