/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ProblemSchema } from './problemSchema';

/**
 * NotFound - the requested resource was not found or you do not have access.
 */
export type NotFoundResponse = ProblemSchema;
