/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { QuizOutput } from './quizOutput';

export interface ParadigmDetailsSchema {
	/**
	 * The id of the person associated with the paradigm
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/**
	 * The name of the person associated with the paradigm
	 * @nullable
	 */
	name: string | null;
	/** The last reviewed timestamp of the paradigm */
	lastReviewed: string | null;
	/**
	 * The content of the paradigm
	 * @nullable
	 */
	paradigm: string | null;
	/** The list of certifications associated with the paradigm */
	certifications?: QuizOutput[];
}
