/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type PersonTournSummaryJudge = {
	categoryName: string;
	/** @nullable */
	schoolName: string | null;
} | null;
