/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ResultSetSchemaHeadersProtocol } from './resultSetSchemaHeadersProtocol';

export type ResultSetSchemaHeaders = {
	[key: string]: {
		tag: string;
		description: string;
		no_sort: boolean;
		sort_desc: boolean;
		Protocol?: ResultSetSchemaHeadersProtocol;
	};
};
