/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Tourn {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** @maxLength 63 */
	name: string;
	city: string | null;
	state: string | null;
	country: string | null;
	/** @maxLength 31 */
	tz: string;
	webname: string;
	hidden: boolean;
	start: string;
	end: string;
	regStart: string;
	regEnd: string;
}
