/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UnlinkedJudgeSchemaType =
	(typeof UnlinkedJudgeSchemaType)[keyof typeof UnlinkedJudgeSchemaType];

export const UnlinkedJudgeSchemaType = {
	judge: 'judge',
	chapter_judge: 'chapter_judge',
} as const;
