/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UnlinkedStudentSearchSchemaChapter } from './unlinkedStudentSearchSchemaChapter';

export interface UnlinkedStudentSearchSchema {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** @nullable */
	first: string | null;
	/** @nullable */
	middle?: string | null;
	/** @nullable */
	last: string | null;
	/** @nullable */
	gradYear?: number | null;
	Chapter: UnlinkedStudentSearchSchemaChapter;
	/** @nullable */
	tournCount: number | null;
}
