/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UnlinkedJudgeSchemaType } from './unlinkedJudgeSchemaType';

export interface UnlinkedJudgeSchema {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	type: UnlinkedJudgeSchemaType;
	/** @nullable */
	first: string | null;
	/** @nullable */
	last: string | null;
	/** @nullable */
	schoolName?: string | null;
	/** @nullable */
	tournName?: string | null;
	/**
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	tournCount?: number;
}
