/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UserStudentsClaimParams = {
	/**
	 * ID of the student to claim
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	studentId?: number;
};
