/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UserJudgesHistoryParams = {
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	limit?: number;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	offset?: number;
};
